#!/bin/bash
instance_name=`hostname -f | cut -d'.' -f1`  #获取本机名，用于后面的的标签

label="count_netstat_wait_connections"  #定义key名

count_netstat_wait_connections=`netstat -an | grep -i wait | wc -l`  #获取数据的命令

echo "$label: $count_netstat_wait_connections"

echo "$label  $count_netstat_wait_connections" | curl --data-binary @- http://10.6.2.116:9091/metrics/job/pushgateway_job/instance/superking


#count_netstat_wait_connections 这个就是后面出图用的 count_netstat_wait_connections{job=~"pushgateway_job"} 或者是count_netstat_wait_connections{instance=~“superking”}
docker run -d -p 9091:9091 prom/pushgateway "--persistence.file=pg_file –-persistence.interval=30s"  后面30s 是因为有延迟 promethues每次都那最新的数据 但是没有数据 就用上次的 多长时间就是这个参数设置的
需要持久就--persistence.file=pg_file    不需要就不加 加后面的

1 重新生成pushgateway 2 curl 接口 删除数据
