#!/usr/bin/python
#encoding=utf8

import sys
reload(sys)
sys.setdefaultencoding("utf8")

import consul
#connect consul
c = consul.Consul(host='47.98.146.101',port=80,scheme='http')  #######一般走内网会好点
#index, data = c.kv.get('php/wangchao/yunwei', index=None)  #php/wangchao/yunwei 在consul里面是一层层目录结构 就是获取这个key
#print(data['Value'])
ALLres = c.kv.get("",recurse=True)

b = [{i["Key"]:i["Value"]} for i in ALLres[1]]
print(b)

def make_dir(somedir,somefile):
	import os
	Dir = "/".join(somedir.split("/")[:-1])
	File = somedir.split("/")[-1]
	Neirong = somefile
	try:
		os.system("mkdir -p %s" %Dir)
		with open(Dir+"/"+File, 'wt') as f:
			f.write(Neirong)	
	except Exception as e:
		print(e)	
[make_dir(i.keys()[0],i.values()[0]) for i in b]


        # in another process
#c.kv.put('foo0/ff/d/s/a', 'bar') ########## 设置 key  和 value

#curl  172.16.128.247:8500/v1/kv/php/wangchao/yunwei?raw=true  ####### curl  拿到key
