#!/usr/local/python3/bin/python3.6
import asyncio

import time

now = lambda: time.time()

async def do_some_work(x):
    print('Waiting: ', x)
    await asyncio.sleep(x)
    return 'Done after {}s'.format(x)

start = now()

coroutine1 = do_some_work(1)
coroutine2 = do_some_work(2)
coroutine3 = do_some_work(4)

tasks = [
    asyncio.ensure_future(coroutine1),
    asyncio.ensure_future(coroutine2),
    asyncio.ensure_future(coroutine3)
]

loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.wait(tasks))

for task in tasks:
    print('Task ret: ', task.result())###task.result是上面函数返回的结果

print('TIME: ', now() - start)



#################################################################   flask 异步类似于多进程   ################################################################
flask application with background threads

from flask import Flask
from time import sleep
from concurrent.futures import ThreadPoolExecutor

# DOCS https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor
executor = ThreadPoolExecutor(2)

app = Flask(__name__)


@app.route('/jobs')
def run_jobs():
    executor.submit(some_long_task1)
    executor.submit(some_long_task2, 'hello', 123)
    return 'Two jobs was launched in background!'


def some_long_task1():
    print("Task #1 started!")
    sleep(10)
    print("Task #1 is done!")


def some_long_task2(arg1, arg2):
    print("Task #2 started with args: %s %s!" % (arg1, arg2))
    sleep(5)
    print("Task #2 is done!")


if __name__ == '__main__':
    app.run()

-----------------------------------------------------------------flask的猴子补丁 类似于异步io-----------------------------------------------------------
from flask import Flask, request, g
import os
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
 
# gevent
from gevent import monkey
from gevent.pywsgi import WSGIServer
monkey.patch_all()
# gevent end
 
app = Flask(__name__)
app.config.update(DEBUG=True)
 
#获取本机电脑名
myname = socket.getfqdn(socket.gethostname(  ))
 
#获取本机ip
myaddr = socket.gethostbyname(myname)
myport = 8912
 
 
@app.route('/test1')       ######## 同时并发10个 curl 172.16.128.247:8912/test1    就使用的一个线程 ---------------------  但是不是立即返回  还是要等待10秒的
def the_test1():
    print "test1 print start"
    time.sleep(10)                  
    print "test1 print after sleep"
    return 'hello asyn'
 
@app.route('/test2')
def the_test2():
    print "test2 print!"
    return 'test2 return'
 
 
 
 
if __name__ == '__main__':
    http_server = WSGIServer((myaddr, myport), app)
    http_server.serve_forever()
