#!/usr/bin/python

a = [["wangchao",1],["wangchao",2],["chaowang",3],["chaowang",4]]

aa = list(set([i[0] for i in a]))

tag = 0

total = []

for i in aa:
	total.append([i])
	for ii in a:
		if i in ii:
			total[tag].append(ii[1])
	tag += 1

print(total)
