#!/usr/bin/python
import subprocess
#import logging
#log = logging.logging()
def run_it(cmd):
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True,
                         stderr=subprocess.PIPE, close_fds=True)
#    log.debug('running:%s' % cmd)
    for line in iter(p.stdout.readline, b''):
        print line,          # print to stdout immediately
    p.stdout.close()
    p.wait()
    if p.returncode != 0:
#        log.critical("Non zero exit code:%s executing: %s" % (p.returncode, cmd))
	pass        
    return p.stdout

run_it("tailf /usr/local/tomcat/kpoint/logs/catalina.out")
