#!/usr/bin/python
#encoding=utf8
import xlrd, xlwt   #xlwt只能写入xls文件 
rows = []   #create an empty list to store rows
book = xlrd.open_workbook('test.xls')  #open the Excel spreadsheet as workbook
sheet = book.sheet_by_index(0)    #get the first sheet
for user in range(1, sheet.nrows):  #iterate 1 to maxrows
     rows.append(list(sheet.row_values(user, 0, sheet.ncols)))  #iterate through the sheet and get data from rows in list
print(rows)
b = rows[1][2].replace(",",'\n')
rows[1][2] = b
print(rows)
import  xlwt


def Makeexcle(i,exclename):
            wbk = xlwt.Workbook()
            sheet = wbk.add_sheet("Sheet1")
            styleBoldRed=xlwt.easyxf('font: color-index red, bold on')
            headerStyle=styleBoldRed
            for i in range(len(rows)):
                for j in range(0, len(rows[i])):
                    sheet.write(i, j, rows[i][j])
            wbk.save("./%s.xls" %(exclename))

Makeexcle(rows,"wangchao")
