#!/bin/bash

a=(172.16.0.189 192.168.1.1 192.168.1.2 192.168.1.3)

len=${#a[@]}


echo "当前数组长度为 $len"

let len=$len-1

for i in `seq 0 $len`;do
	ip=${a[$i]}
	echo $ip
done



var=hack.fun.book.txt
####  右---->左 第一个.后面的字符串
echo ${var%.*}
#hack.fun.book
####  右---->左 最后一个.后面的字符串
echo ${var%%.*}
#hack
####  左---->右 第一个.后面的字符串
echo ${var#*.}
#fun.book.txt
####  左---->右 最后一个.后面的字符串
echo ${var##*.}
#txt

--------------------------------shell 字典---------------------
declare -A dic
dic=([key1]="value1" [key2]="value2" [key3]="value3")
echo ${dic["key3"]}
value3
echo ${dic["key1"]}
value1
echo ${dic["key2"]}
value2

