#!/usr/bin/python
#encoding=utf8
from BaseHTTPServer import BaseHTTPRequestHandler,HTTPServer
import json
from vpc_server import start_createvpc
import urlparse

class DemoHttpServer(BaseHTTPRequestHandler):

    def do_GET(self):
        parsed_path = urlparse.urlparse(self.path)
        if parsed_path.path != '/create_vpc':
            self.send_error(404, "Page not Found!")
            return
	try:
		res = str(start_createvpc(parsed_path.query))
	except:
		res = {"code":500,"data":"args is Error"}
        self.send_response(200, message='OK')
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps(res))
        
        
if __name__ == '__main__':
    server = HTTPServer(('0.0.0.0', 8008), DemoHttpServer)
    print('Server is running, user <Ctrl+C> to srop.')
    server.serve_forever()

